export const EMOJI_RECOMMENDATIONS: { [key: string]: string } = {
  'Matematika': '🔢',
  'Ingliz tili': '🇬🇧',
  'O\'zbek tili': '🇺🇿',
  'Fizika': '⚛️',
  'Kimya': '🧪',
  'Biologiya': '🦠',
  'Tarix': '📜',
  'Geografiya': '🌍',
  'Adabiyot': '📖',
  'Musiqa': '🎵',
  'Rasmni chizish': '🎨',
  'Jismoniy madaniyat': '🏃',
  'Informatika': '💻',
  'O\'z vatan tarixi': '🏛️',
  'Sharqiy tillar': '📚',
  'Fransuz tili': '🇫🇷',
  'Nemis tili': '🇩🇪',
  'Rus tili': '🇷🇺',
  'Yapon tili': '🇯🇵',
  'Xitoy tili': '🇨🇳',
  'Iqtisodiyot': '💼',
  'Huquq': '⚖️',
  'Psixologiya': '🧠',
  'Jamiyat fanlar': '👥',
  'Ekologiya': '🌱',
  'Astronomiya': '⭐',
  'Mehnat': '🔧',
  'Ruh va axloq': '✨',
  'Ingliz adabiyoti': '📕',
  'San\'at': '🖼️',
};